### ISSUE TITLE
Node name is constantly cleared while scene is loaded

### ISSUE THREAD

**Issue by halbe** [mbrea-c/bevy_animation_graph#74]
When I open the editor and a graph then try and create a node, everything works fine. If I do so after having first opened a scene to preview, anything I type into the "name" field under "Create node" is cleared as soon as I type (I see the text for an instant before it disappears). Regarding #6 this happens regardless of whether the scene successfully loaded.

Workaround: create a node with a blank name then write the name into it afterwards.

**Comment by halbe** [comment]
Have not been able to replicate this after using the editor more today, not sure what changed.

**Comment by mbrea-c** [comment]
Interesting. It seems that if a scene is loaded and the graph inspector is active with the "Create node" menu open, what you described happens for _every_ text field in the screen (e.g. the separate send events widget is also affected). However, if either the scene preview is stopped or the create node menu is hidden (for example, by clicking on a node, which activates the node inspector) then everything goes back to normal.

Seems like the issue is conflicting UI element ids. The linked PR should fix it.
